[package]
name = "wasm_type_gen_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.52"
syn = { version = "2", features = ["extra-traits"] }
quote = "1"

[lib]
proc-macro = true
