[package]
name = "wasm_type_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm_type_gen_derive = { path = "../wasm_type_gen_derive" }
wasmtime = "7.0.0"
